package main

import (
	"fmt"
	"io"
	"os"
)

// cmdCompletion prints a shell completion script to stdout. It takes exactly
// one operand — the shell — mirroring `<tool> completion <shell>` elsewhere.
func cmdCompletion(args []string) {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: yas completion zsh")
		os.Exit(2)
	}
	if err := doCompletion(os.Stdout, args[0]); err != nil {
		fmt.Fprintf(os.Stderr, "yas completion: %v\n", err)
		os.Exit(2)
	}
}

// doCompletion writes the completion script for the named shell to w. zsh is
// the only supported shell today; the error names the supported set so the
// CLI surface stays self-documenting as shells are added.
func doCompletion(w io.Writer, shell string) error {
	if shell != "zsh" {
		return fmt.Errorf("unsupported shell %q (supported: zsh)", shell)
	}
	_, err := io.WriteString(w, zshCompletionScript)
	return err
}

// zshCompletionScript is hand-maintained against route()'s command switch and
// each cmd*'s flag set; TestDoCompletion_ZshOffersEveryCommand keeps the
// command list honest and `zsh -n` guards the syntax.
const zshCompletionScript = `#compdef yas
# zsh completion for yas — generated by ` + "`yas completion zsh`" + `.
#
# Install into any directory on $fpath:
#   yas completion zsh > "${fpath[1]}/_yas"
# or source it from .zshrc (after compinit):
#   source <(yas completion zsh)

_yas() {
  local -a subcmds=(
    'record:record a command start/finish (used by the shell hook)'
    'search:full-text search across history'
    'history:list recent entries (the default command)'
    'session:show one shell session as a linear timeline'
    'serve:run the localhost HTTP+JSON query API'
    'sync:push/pull with the central server'
    'import:backfill from shell history or atuin'
    'mcp:run the MCP server (read-only tools) over stdio/HTTP'
    'completion:print a shell completion script'
    'version:print the yas version'
    'help:show usage'
  )

  if (( CURRENT == 2 )); then
    _describe -t commands 'yas command' subcmds
    return
  fi

  case ${words[2]} in
    record)
      if (( CURRENT == 3 )); then
        local -a actions=(
          'start:persist a started command and print its id'
          'finish:stamp the exit code and duration onto a record'
        )
        _describe -t actions 'record action' actions
        return
      fi
      case ${words[3]} in
        start)
          _arguments \
            '--command[the command line to record]:command:' \
            '--cwd[working directory]:directory:_files -/' \
            '--session[session id]:session:' \
            '--shell[recording shell]:shell:' \
            '--author[executor recording the command]:author:'
          ;;
        finish)
          _arguments \
            '--id[record id printed by start]:id:' \
            '--exit[exit code]:code:' \
            '--duration-ms[duration in milliseconds]:ms:'
          ;;
      esac
      ;;
    search)
      _arguments \
        '--host[filter by host]:host:' \
        '--cwd[filter by working directory]:directory:_files -/' \
        '--session[filter by session id]:session:' \
        '--exit[filter by exit code]:code:' \
        '--failed[only non-zero exits]' \
        '--executor[filter by executor]:executor:' \
        '--since[start of time range]:time:' \
        '--until[end of time range]:time:' \
        '--limit[maximum results]:count:' \
        '--offset[skip the first n results]:count:' \
        '--reverse[oldest first]' \
        '--json[emit the query-API JSON envelope]' \
        '--no-color[disable ANSI colors]' \
        '--no-session[hide the session column]' \
        '*:search text:'
      ;;
    history)
      _arguments \
        '-d[delete an entry or range by number]:offset or start-end:' \
        '-c[delete ALL history]' \
        '--yes[confirm the -c clear]' \
        '--time-format[Go time layout for timestamps]:layout:' \
        '--no-time[hide the time column]' \
        '--no-exit[hide the exit column]' \
        '--no-session[hide the session column]' \
        '--no-color[disable ANSI colors]' \
        '--json[emit the query-API JSON envelope]' \
        '::count:'
      ;;
    session)
      _arguments \
        '--json[emit the query-API JSON envelope]' \
        '--no-color[disable ANSI colors]' \
        '--time-format[Go time layout for timestamps]:layout:' \
        '--no-time[hide the time column]' \
        '--no-exit[hide the exit column]' \
        '::session token or id:'
      ;;
    serve)
      _arguments '--addr[listen address]:address:'
      ;;
    import)
      _arguments \
        '--from[history source format]:source:(zsh-history atuin)' \
        '--file[history source path]:file:_files'
      ;;
    mcp)
      _arguments \
        '--http[serve MCP over HTTP at this address]:address:' \
        '--http-allow-insecure[allow --http to bind a non-loopback address]'
      ;;
    completion)
      if (( CURRENT == 3 )); then
        _values 'shell' 'zsh[zsh completion script]'
      fi
      ;;
  esac
}

# Work both as an fpath-autoloaded compdef file and when sourced directly.
if [[ ${funcstack[1]} == _yas ]]; then
  _yas "$@"
else
  compdef _yas yas
fi
`
